# Generated by Django 3.1.7 on 2021-03-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210312_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='liked_posts',
            new_name='lposts',
        ),
    ]
